services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile_jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      deploy-network:
        ipv4_address: 172.32.0.2  # Assign a static IP to Jenkins

  mongo:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      deploy-network:
        ipv4_address: 172.32.0.4  # Assign a static IP to Mongo

  deploy-container:
    build:
      context: .
      dockerfile: Dockerfile_deploy-env
    container_name: node20-deploy-container
    ports:
      - "4200:4200"
      - "2222:22"
    networks:
      deploy-network:
        ipv4_address: 172.32.0.3  # Assign a static IP to deploy container
    command: ["/bin/bash", "-c", "/usr/sbin/sshd && /bin/bash"]
    tty: true
    stdin_open: true

networks:
  deploy-network:
    name: deploy-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
